# Modeling for the Patent Classification Project

The code for modeling the text in the claims data

In [1]:
var df = spark.read.load("../Projects/data/vec_df_hdfs")

In [2]:
import org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator
import org.apache.spark.ml.classification.NaiveBayes

var Array(train, test) = df.randomSplit(Array(.8, .2), 42)
var eval = new MulticlassClassificationEvaluator()
    .setLabelCol("label")
    .setPredictionCol("prediction")
    .setMetricName("accuracy")

var nb = new NaiveBayes()
var cs = new org.apache.spark.text.similarity.CosineSimilarity()

In [3]:
var nb_model = nb.fit(train)

+--------------------+
|            features|
+--------------------+
|(262144,[0,1,2,6,...|
|(262144,[0,1,3,4,...|
|(262144,[0,1,2,9,...|
|(262144,[0,1,2,8,...|
|(262144,[0,1,2,6,...|
|(262144,[0,2,6,7,...|
|(262144,[0,1,2,6,...|
|(262144,[0,1,2,3,...|
|(262144,[0,1,2,3,...|
|(262144,[0,1,2,6,...|
|(262144,[0,1,2,9,...|
|(262144,[0,1,2,6,...|
|(262144,[0,2,3,4,...|
|(262144,[0,3,4,7,...|
|(262144,[0,1,2,3,...|
|(262144,[0,1,2,3,...|
|(262144,[0,1,2,7,...|
|(262144,[0,1,2,3,...|
|(262144,[0,1,2,6,...|
|(262144,[1,2,6,8,...|
+--------------------+
only showing top 20 rows



In [4]:
var nb_preds = nb_model.transform(test)

In [5]:
eval.evaluate(nb_preds)

.687

The accuracy score for Naive Bayes is .687

In [7]:
var cs_model = cs.fit(train)

In [9]:
var cs_preds = cs_model.transform(test)

In [8]:
eval.evaluate(cs_preds)

.712

The accuracy score for Cosine Similarity is .712